# Generated by Django 5.0.8 on 2024-08-19 21:51

import datetime
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('duedate', models.DateField(default=home.models.get_default_duedate)),
                ('description', models.CharField(max_length=500)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('priority', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(related_name='operas', to='home.members')),
            ],
        ),
    ]
